### PR TITLE
[14.0][ADD] website_sale_full_witdh

### PR DESCRIPTION
**Pull request by Anxo82**

### CODE REVIEW

**Comment by Anxo82** [comment]
@dalonsod Review please.
Thanks

**Comment by dalonsod** [comment]
This addon depends on `website_sale`, but a I don't see any reference on this (manifest excluded), why can we see if SCSS affects (and only affects) to search & product website pages, and not to other unexpected parts of Odoo? In other words, could you provide a link to `website_sale` code that originally restricts pages width?

**Comment by Anxo82** [comment]
@dalonsod Updated the CSS declaration to include the .oe_website_sale class, so the rule now only applies to elements with both .container and .oe_website_sale classes. The .oe_website_sale class depends "website_sale" https://github.com/odoo/odoo/blob/f2765d2cab5671a010404c36842bf1b4c4d6350b/addons/website_sale/static/src/scss/website_sale.scss#L17C1-L17C17

**Comment by dalonsod** [comment]
:+1: 

@ChristianSantamaria  could you install it in ArvTest environment?

**Comment by ChristianSantamaria** [comment]
Done :+1:

**Comment by dalonsod** [comment]
Tested :+1:, let's merge!

**Pull request merged**
