### PR TITLE
[13.0][ADD] website_sale_stock_warehouses

### PR DESCRIPTION
**Pull request by dalonsod**
This module adds custom warehouses for website stock computing, replacing the current warehouse (only one selectable) to a multiple selection.
For further instructions, see `README` file.

@lmiguens-solvos could you test? This addon also fixes cart update quantity "bug".
cc @ChristianSantamaria

### CODE REVIEW

**Comment by lmiguens-solvos** [comment]
> @lmiguens-solvos could you test? This addon also fixes cart update quantity "bug".

Tested! And LGTM.
Just comment that when paying the order by transfer the order is not confirmed, and as long as the stock available on the web is not confirmed it does not change ... but I think that we can not avoid it... 
or... do you have any idea

**Comment by dalonsod** [comment]
@lmiguens-solvos fixed some decoration bugs

**Review by lmiguens-solvos — APPROVED** [review]
LGTM

**Comment by dalonsod** [comment]
Merging!

**Pull request merged**
